services:
  api-gateway:
    build:
      context: ./services/api-gateway
    ports:
      - "3000:3000"
    env_file:
      - .env

  aws-audit:
    build:
      context: ./services/aws-audit
    ports:
      - "3001:3001"
    env_file:
      - .env

  slack-bot:
    build:
      context: ./services/slack-bot
    ports:
      - "3002:3002"
    env_file:
      - .env
