{
 "title": "Cloud Attack Surface Scanner - Observability",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Live CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Event Loop Lag (Health)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "Event Loop Lag" }
   ]
  },
  {
   "title": "Heap Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "Heap Used" }
   ]
  },
  {
   "title": "Heap Memory per Replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}