# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Monitor the CASS backend across 3 pod replicas
  - job_name: "scanner-app"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["host.docker.internal:3000"]
