# 1. The Deployment (Updated with Docker Hub image)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-app
spec:
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
        - name: scanner
          image: aayushpandey29/scanner-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: AWS_REGION
              value: "ap-south-1"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---
# 2. The Service (Unchanged)
apiVersion: v1
kind: Service
metadata:
  name: scanner-service
spec:
  selector:
    app: scanner
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP

---
# 3. NEW: The Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scanner-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scanner-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
